target_name: ''
group_name: right_arm
end_effector: right_sdh
possible_grasps: 
  - 
    id: Grasp0
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 446998970
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447018324
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447028417
        frame_id: world_link
      pose: 
        position: 
          x: -2.32682891838e-17
          y: -0.19
          z: 0.205
        orientation: 
          x: -0.5
          y: 0.5
          z: 0.5
          w: 0.5
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447026863
          frame_id: world_link
        vector: 
          x: -8.32471621362e-17
          y: -0.67976466516
          z: 0.73343029662
      desired_distance: 0.279508501291
      min_distance: 0.195655941963
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447027695
          frame_id: world_link
        vector: 
          x: 8.32471621362e-17
          y: 0.67976466516
          z: -0.73343029662
      desired_distance: 0.279508501291
      min_distance: 0.195655941963
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp1
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447051950
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447060154
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447068428
        frame_id: world_link
      pose: 
        position: 
          x: -0.0297225483576
          y: -0.187660784713
          z: 0.205
        orientation: 
          x: -0.459229119003
          y: 0.53768821473
          z: 0.459229119003
          w: 0.53768821473
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447067380
          frame_id: world_link
        vector: 
          x: -0.14533499731
          y: 0.989382503664
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447067982
          frame_id: world_link
        vector: 
          x: 0.14533499731
          y: -0.989382503664
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp2
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447077203
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447084083
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447091896
        frame_id: world_link
      pose: 
        position: 
          x: -0.0587132289312
          y: -0.180700738096
          z: 0.205
        orientation: 
          x: -0.415626937777
          y: 0.572061402818
          z: 0.415626937777
          w: 0.572061402818
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447090818
          frame_id: world_link
        vector: 
          x: 0.0112278403577
          y: 0.999936965814
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447091365
          frame_id: world_link
        vector: 
          x: -0.0112278403577
          y: -0.999936965814
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp3
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447100465
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447106414
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447113605
        frame_id: world_link
      pose: 
        position: 
          x: -0.0862581949505
          y: -0.169291239596
          z: 0.205
        orientation: 
          x: -0.369462278271
          y: 0.602907642127
          z: 0.369462278271
          w: 0.602907642127
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447112613
          frame_id: world_link
        vector: 
          x: 0.167514211332
          y: 0.985869661264
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447113149
          frame_id: world_link
        vector: 
          x: -0.167514211332
          y: -0.985869661264
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp4
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447121287
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447127226
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447133821
        frame_id: world_link
      pose: 
        position: 
          x: -0.111679197936
          y: -0.153713228931
          z: 0.205
        orientation: 
          x: -0.32101976096
          y: 0.630036755335
          z: 0.32101976096
          w: 0.630036755335
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447132909
          frame_id: world_link
        vector: 
          x: 0.319675826476
          y: 0.947526973741
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447133410
          frame_id: world_link
        vector: 
          x: -0.319675826476
          y: -0.947526973741
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp5
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447142546
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447148549
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447155104
        frame_id: world_link
      pose: 
        position: 
          x: -0.134350288425
          y: -0.134350288425
          z: 0.205
        orientation: 
          x: -0.270598050073
          y: 0.653281482438
          z: 0.270598050073
          w: 0.653281482438
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447154212
          frame_id: world_link
        vector: 
          x: 0.463965961829
          y: 0.885853027462
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447154688
          frame_id: world_link
        vector: 
          x: -0.463965961829
          y: -0.885853027462
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp6
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447162521
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447168379
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447174899
        frame_id: world_link
      pose: 
        position: 
          x: -0.153713228931
          y: -0.111679197936
          z: 0.205
        orientation: 
          x: -0.218508012224
          y: 0.672498511964
          z: 0.218508012224
          w: 0.672498511964
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447174012
          frame_id: world_link
        vector: 
          x: 0.596831715387
          y: 0.80236643967
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447174488
          frame_id: world_link
        vector: 
          x: -0.596831715387
          y: -0.80236643967
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp7
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447182075
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447187633
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447193992
        frame_id: world_link
      pose: 
        position: 
          x: -0.169291239596
          y: -0.0862581949505
          z: 0.205
        orientation: 
          x: -0.165070799819
          y: 0.687569364535
          z: 0.165070799819
          w: 0.687569364535
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447193080
          frame_id: world_link
        vector: 
          x: 0.715001491341
          y: 0.699122927231
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447193581
          frame_id: world_link
        vector: 
          x: -0.715001491341
          y: -0.699122927231
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp8
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447201239
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447206766
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447213181
        frame_id: world_link
      pose: 
        position: 
          x: -0.180700738096
          y: -0.0587132289312
          z: 0.205
        orientation: 
          x: -0.110615871041
          y: 0.698401123334
          z: 0.110615871041
          w: 0.698401123334
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447212164
          frame_id: world_link
        vector: 
          x: 0.815565557624
          y: 0.578664688068
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447212725
          frame_id: world_link
        vector: 
          x: -0.815565557624
          y: -0.578664688068
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp9
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447220658
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447226967
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447233412
        frame_id: world_link
      pose: 
        position: 
          x: -0.187660784713
          y: -0.0297225483576
          z: 0.205
        orientation: 
          x: -0.0554789586349
          y: 0.704927006965
          z: 0.0554789586349
          w: 0.704927006965
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447232500
          frame_id: world_link
        vector: 
          x: 0.896047693172
          y: 0.443957803807
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447233001
          frame_id: world_link
        vector: 
          x: -0.896047693172
          y: -0.443957803807
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp10
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447241004
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447246506
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198293
          nsecs: 447252966
        frame_id: world_link
      pose: 
        position: 
          x: -0.19
          y: 1.16341445919e-17
          z: 0.205
        orientation: 
          x: 5.55111512313e-17
          y: 0.707106781187
          z: -5.55111512313e-17
          w: 0.707106781187
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447251979
          frame_id: world_link
        vector: 
          x: 0.954466160702
          y: 0.298319205004
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198293
            nsecs: 447252545
          frame_id: world_link
        vector: 
          x: -0.954466160702
          y: -0.298319205004
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
support_surface_name: table_surface_link
allow_gripper_support_collision: True
attached_object_touch_links: []
minimize_object_distance: False
path_constraints: 
  name: ''
  joint_constraints: []
  position_constraints: []
  orientation_constraints: []
  visibility_constraints: []
planner_id: KPIECEkConfigDefault
allowed_touch_objects: []
allowed_planning_time: 5.0
planning_options: 
  planning_scene_diff: 
    name: ''
    robot_state: 
      joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        name: []
        position: []
        velocity: []
        effort: []
      multi_dof_joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        joint_names: []
        transforms: []
        twist: []
        wrench: []
      attached_collision_objects: []
      is_diff: True
    robot_model_name: ''
    fixed_frame_transforms: []
    allowed_collision_matrix: 
      entry_names: []
      entry_values: []
      default_entry_names: []
      default_entry_values: []
    link_padding: []
    link_scale: []
    object_colors: []
    world: 
      collision_objects: []
      octomap: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        origin: 
          position: 
            x: 0.0
            y: 0.0
            z: 0.0
          orientation: 
            x: 0.0
            y: 0.0
            z: 0.0
            w: 0.0
        octomap: 
          header: 
            seq: 0
            stamp: 
              secs: 0
              nsecs: 0
            frame_id: ''
          binary: False
          id: ''
          resolution: 0.0
          data: []
    is_diff: True
  plan_only: True
  look_around: False
  look_around_attempts: 0
  max_safe_execution_cost: 0.0
  replan: False
  replan_attempts: 0
  replan_delay: 2.0
---
target_name: ''
group_name: right_arm
end_effector: right_sdh
possible_grasps: 
  - 
    id: Grasp0
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279652263
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279662828
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279670119
        frame_id: world_link
      pose: 
        position: 
          x: -2.32682891838e-17
          y: -0.19
          z: 0.205
        orientation: 
          x: -0.5
          y: 0.5
          z: 0.5
          w: 0.5
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279669145
          frame_id: world_link
        vector: 
          x: -8.32471621362e-17
          y: -0.67976466516
          z: 0.73343029662
      desired_distance: 0.279508501291
      min_distance: 0.195655941963
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279669550
          frame_id: world_link
        vector: 
          x: 8.32471621362e-17
          y: 0.67976466516
          z: -0.73343029662
      desired_distance: 0.279508501291
      min_distance: 0.195655941963
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp1
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279679817
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279684648
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279690596
        frame_id: world_link
      pose: 
        position: 
          x: -0.0297225483576
          y: -0.187660784713
          z: 0.205
        orientation: 
          x: -0.459229119003
          y: 0.53768821473
          z: 0.459229119003
          w: 0.53768821473
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279689736
          frame_id: world_link
        vector: 
          x: -0.14533499731
          y: 0.989382503664
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279690142
          frame_id: world_link
        vector: 
          x: 0.14533499731
          y: -0.989382503664
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp2
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279697307
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279702067
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279707033
        frame_id: world_link
      pose: 
        position: 
          x: -0.0587132289312
          y: -0.180700738096
          z: 0.205
        orientation: 
          x: -0.415626937777
          y: 0.572061402818
          z: 0.415626937777
          w: 0.572061402818
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279706197
          frame_id: world_link
        vector: 
          x: 0.0112278403577
          y: 0.999936965814
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279706670
          frame_id: world_link
        vector: 
          x: -0.0112278403577
          y: -0.999936965814
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp3
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279713353
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279717467
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279722329
        frame_id: world_link
      pose: 
        position: 
          x: -0.0862581949505
          y: -0.169291239596
          z: 0.205
        orientation: 
          x: -0.369462278271
          y: 0.602907642127
          z: 0.369462278271
          w: 0.602907642127
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279721568
          frame_id: world_link
        vector: 
          x: 0.167514211332
          y: 0.985869661264
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279721997
          frame_id: world_link
        vector: 
          x: -0.167514211332
          y: -0.985869661264
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp4
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279728599
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279732635
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279737364
        frame_id: world_link
      pose: 
        position: 
          x: -0.111679197936
          y: -0.153713228931
          z: 0.205
        orientation: 
          x: -0.32101976096
          y: 0.630036755335
          z: 0.32101976096
          w: 0.630036755335
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279736650
          frame_id: world_link
        vector: 
          x: 0.319675826476
          y: 0.947526973741
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279737033
          frame_id: world_link
        vector: 
          x: -0.319675826476
          y: -0.947526973741
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp5
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279743483
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279747876
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279752418
        frame_id: world_link
      pose: 
        position: 
          x: -0.134350288425
          y: -0.134350288425
          z: 0.205
        orientation: 
          x: -0.270598050073
          y: 0.653281482438
          z: 0.270598050073
          w: 0.653281482438
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279751648
          frame_id: world_link
        vector: 
          x: 0.463965961829
          y: 0.885853027462
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279752063
          frame_id: world_link
        vector: 
          x: -0.463965961829
          y: -0.885853027462
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp6
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279758724
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279763184
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279767833
        frame_id: world_link
      pose: 
        position: 
          x: -0.153713228931
          y: -0.111679197936
          z: 0.205
        orientation: 
          x: -0.218508012224
          y: 0.672498511964
          z: 0.218508012224
          w: 0.672498511964
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279767167
          frame_id: world_link
        vector: 
          x: 0.596831715387
          y: 0.80236643967
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279767524
          frame_id: world_link
        vector: 
          x: -0.596831715387
          y: -0.80236643967
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp7
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279774137
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279778308
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279783228
        frame_id: world_link
      pose: 
        position: 
          x: -0.169291239596
          y: -0.0862581949505
          z: 0.205
        orientation: 
          x: -0.165070799819
          y: 0.687569364535
          z: 0.165070799819
          w: 0.687569364535
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279782421
          frame_id: world_link
        vector: 
          x: 0.715001491341
          y: 0.699122927231
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279782862
          frame_id: world_link
        vector: 
          x: -0.715001491341
          y: -0.699122927231
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp8
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279789373
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279793240
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279797562
        frame_id: world_link
      pose: 
        position: 
          x: -0.180700738096
          y: -0.0587132289312
          z: 0.205
        orientation: 
          x: -0.110615871041
          y: 0.698401123334
          z: 0.110615871041
          w: 0.698401123334
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279796857
          frame_id: world_link
        vector: 
          x: 0.815565557624
          y: 0.578664688068
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279797243
          frame_id: world_link
        vector: 
          x: -0.815565557624
          y: -0.578664688068
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp9
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279804151
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279808671
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279814069
        frame_id: world_link
      pose: 
        position: 
          x: -0.187660784713
          y: -0.0297225483576
          z: 0.205
        orientation: 
          x: -0.0554789586349
          y: 0.704927006965
          z: 0.0554789586349
          w: 0.704927006965
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279813350
          frame_id: world_link
        vector: 
          x: 0.896047693172
          y: 0.443957803807
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279813742
          frame_id: world_link
        vector: 
          x: -0.896047693172
          y: -0.443957803807
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp10
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279820282
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279824609
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 279829805
        frame_id: world_link
      pose: 
        position: 
          x: -0.19
          y: 1.16341445919e-17
          z: 0.205
        orientation: 
          x: 5.55111512313e-17
          y: 0.707106781187
          z: -5.55111512313e-17
          w: 0.707106781187
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279828991
          frame_id: world_link
        vector: 
          x: 0.954466160702
          y: 0.298319205004
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 279829378
          frame_id: world_link
        vector: 
          x: -0.954466160702
          y: -0.298319205004
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
support_surface_name: table_surface_link
allow_gripper_support_collision: True
attached_object_touch_links: []
minimize_object_distance: False
path_constraints: 
  name: ''
  joint_constraints: []
  position_constraints: []
  orientation_constraints: []
  visibility_constraints: []
planner_id: KPIECEkConfigDefault
allowed_touch_objects: []
allowed_planning_time: 5.0
planning_options: 
  planning_scene_diff: 
    name: ''
    robot_state: 
      joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        name: []
        position: []
        velocity: []
        effort: []
      multi_dof_joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        joint_names: []
        transforms: []
        twist: []
        wrench: []
      attached_collision_objects: []
      is_diff: True
    robot_model_name: ''
    fixed_frame_transforms: []
    allowed_collision_matrix: 
      entry_names: []
      entry_values: []
      default_entry_names: []
      default_entry_values: []
    link_padding: []
    link_scale: []
    object_colors: []
    world: 
      collision_objects: []
      octomap: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        origin: 
          position: 
            x: 0.0
            y: 0.0
            z: 0.0
          orientation: 
            x: 0.0
            y: 0.0
            z: 0.0
            w: 0.0
        octomap: 
          header: 
            seq: 0
            stamp: 
              secs: 0
              nsecs: 0
            frame_id: ''
          binary: False
          id: ''
          resolution: 0.0
          data: []
    is_diff: True
  plan_only: True
  look_around: False
  look_around_attempts: 0
  max_safe_execution_cost: 0.0
  replan: False
  replan_attempts: 0
  replan_delay: 2.0
---
target_name: ''
group_name: right_arm
end_effector: right_sdh
possible_grasps: 
  - 
    id: Grasp0
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 992950594
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 992961041
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 992968678
        frame_id: world_link
      pose: 
        position: 
          x: -2.32682891838e-17
          y: -0.19
          z: 0.205
        orientation: 
          x: -0.5
          y: 0.5
          z: 0.5
          w: 0.5
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 992967809
          frame_id: world_link
        vector: 
          x: -8.32471621362e-17
          y: -0.67976466516
          z: 0.73343029662
      desired_distance: 0.279508501291
      min_distance: 0.195655941963
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 992968244
          frame_id: world_link
        vector: 
          x: 8.32471621362e-17
          y: 0.67976466516
          z: -0.73343029662
      desired_distance: 0.279508501291
      min_distance: 0.195655941963
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp1
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 992978253
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 992983445
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 992988864
        frame_id: world_link
      pose: 
        position: 
          x: -0.0297225483576
          y: -0.187660784713
          z: 0.205
        orientation: 
          x: -0.459229119003
          y: 0.53768821473
          z: 0.459229119003
          w: 0.53768821473
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 992988085
          frame_id: world_link
        vector: 
          x: -0.14533499731
          y: 0.989382503664
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 992988443
          frame_id: world_link
        vector: 
          x: 0.14533499731
          y: -0.989382503664
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp2
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 992994851
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 992999345
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993004058
        frame_id: world_link
      pose: 
        position: 
          x: -0.0587132289312
          y: -0.180700738096
          z: 0.205
        orientation: 
          x: -0.415626937777
          y: 0.572061402818
          z: 0.415626937777
          w: 0.572061402818
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993003397
          frame_id: world_link
        vector: 
          x: 0.0112278403577
          y: 0.999936965814
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993003761
          frame_id: world_link
        vector: 
          x: -0.0112278403577
          y: -0.999936965814
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp3
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993009905
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993014272
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993018869
        frame_id: world_link
      pose: 
        position: 
          x: -0.0862581949505
          y: -0.169291239596
          z: 0.205
        orientation: 
          x: -0.369462278271
          y: 0.602907642127
          z: 0.369462278271
          w: 0.602907642127
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993018210
          frame_id: world_link
        vector: 
          x: 0.167514211332
          y: 0.985869661264
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993018591
          frame_id: world_link
        vector: 
          x: -0.167514211332
          y: -0.985869661264
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp4
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993024274
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993028270
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993032871
        frame_id: world_link
      pose: 
        position: 
          x: -0.111679197936
          y: -0.153713228931
          z: 0.205
        orientation: 
          x: -0.32101976096
          y: 0.630036755335
          z: 0.32101976096
          w: 0.630036755335
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993032212
          frame_id: world_link
        vector: 
          x: 0.319675826476
          y: 0.947526973741
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993032576
          frame_id: world_link
        vector: 
          x: -0.319675826476
          y: -0.947526973741
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp5
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993037922
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993042125
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993046485
        frame_id: world_link
      pose: 
        position: 
          x: -0.134350288425
          y: -0.134350288425
          z: 0.205
        orientation: 
          x: -0.270598050073
          y: 0.653281482438
          z: 0.270598050073
          w: 0.653281482438
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993045896
          frame_id: world_link
        vector: 
          x: 0.463965961829
          y: 0.885853027462
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993046214
          frame_id: world_link
        vector: 
          x: -0.463965961829
          y: -0.885853027462
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp6
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993051676
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993055525
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993060289
        frame_id: world_link
      pose: 
        position: 
          x: -0.153713228931
          y: -0.111679197936
          z: 0.205
        orientation: 
          x: -0.218508012224
          y: 0.672498511964
          z: 0.218508012224
          w: 0.672498511964
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993059705
          frame_id: world_link
        vector: 
          x: 0.596831715387
          y: 0.80236643967
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993060015
          frame_id: world_link
        vector: 
          x: -0.596831715387
          y: -0.80236643967
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp7
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993065180
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993069343
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993073669
        frame_id: world_link
      pose: 
        position: 
          x: -0.169291239596
          y: -0.0862581949505
          z: 0.205
        orientation: 
          x: -0.165070799819
          y: 0.687569364535
          z: 0.165070799819
          w: 0.687569364535
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993073065
          frame_id: world_link
        vector: 
          x: 0.715001491341
          y: 0.699122927231
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993073396
          frame_id: world_link
        vector: 
          x: -0.715001491341
          y: -0.699122927231
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp8
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993078534
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993082767
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993087127
        frame_id: world_link
      pose: 
        position: 
          x: -0.180700738096
          y: -0.0587132289312
          z: 0.205
        orientation: 
          x: -0.110615871041
          y: 0.698401123334
          z: 0.110615871041
          w: 0.698401123334
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993086508
          frame_id: world_link
        vector: 
          x: 0.815565557624
          y: 0.578664688068
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993086846
          frame_id: world_link
        vector: 
          x: -0.815565557624
          y: -0.578664688068
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp9
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993092542
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993096765
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993101159
        frame_id: world_link
      pose: 
        position: 
          x: -0.187660784713
          y: -0.0297225483576
          z: 0.205
        orientation: 
          x: -0.0554789586349
          y: 0.704927006965
          z: 0.0554789586349
          w: 0.704927006965
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993100534
          frame_id: world_link
        vector: 
          x: 0.896047693172
          y: 0.443957803807
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993100888
          frame_id: world_link
        vector: 
          x: -0.896047693172
          y: -0.443957803807
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: Grasp10
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993106170
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932, -0.7853981852531433, 0.3490658402442932]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993110450
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622, -0.22439947724342346, 0.5235987901687622]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 1397198295
          nsecs: 993114662
        frame_id: world_link
      pose: 
        position: 
          x: -0.19
          y: 1.16341445919e-17
          z: 0.205
        orientation: 
          x: 5.55111512313e-17
          y: 0.707106781187
          z: -5.55111512313e-17
          w: 0.707106781187
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993114038
          frame_id: world_link
        vector: 
          x: 0.954466160702
          y: 0.298319205004
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 1397198295
            nsecs: 993114362
          frame_id: world_link
        vector: 
          x: -0.954466160702
          y: -0.298319205004
          z: 0.0
      desired_distance: 0.204510599375
      min_distance: 0.143157422543
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
support_surface_name: table_surface_link
allow_gripper_support_collision: True
attached_object_touch_links: []
minimize_object_distance: False
path_constraints: 
  name: ''
  joint_constraints: []
  position_constraints: []
  orientation_constraints: []
  visibility_constraints: []
planner_id: KPIECEkConfigDefault
allowed_touch_objects: []
allowed_planning_time: 5.0
planning_options: 
  planning_scene_diff: 
    name: ''
    robot_state: 
      joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        name: []
        position: []
        velocity: []
        effort: []
      multi_dof_joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        joint_names: []
        transforms: []
        twist: []
        wrench: []
      attached_collision_objects: []
      is_diff: True
    robot_model_name: ''
    fixed_frame_transforms: []
    allowed_collision_matrix: 
      entry_names: []
      entry_values: []
      default_entry_names: []
      default_entry_values: []
    link_padding: []
    link_scale: []
    object_colors: []
    world: 
      collision_objects: []
      octomap: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        origin: 
          position: 
            x: 0.0
            y: 0.0
            z: 0.0
          orientation: 
            x: 0.0
            y: 0.0
            z: 0.0
            w: 0.0
        octomap: 
          header: 
            seq: 0
            stamp: 
              secs: 0
              nsecs: 0
            frame_id: ''
          binary: False
          id: ''
          resolution: 0.0
          data: []
    is_diff: True
  plan_only: True
  look_around: False
  look_around_attempts: 0
  max_safe_execution_cost: 0.0
  replan: False
  replan_attempts: 0
  replan_delay: 2.0
---
