target_name: cylinder1
group_name: right_arm
end_effector: right_sdh
possible_grasps: 
  - 
    id: Grasp0
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539344817
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539368190
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -2.32682891838e-17
          y: -0.19
          z: 0.205
        orientation: 
          x: -0.5
          y: 0.5
          z: 0.5
          w: 0.5
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp1
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539344817
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539368190
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.0297225483576
          y: -0.187660784713
          z: 0.205
        orientation: 
          x: -0.459229119003
          y: 0.53768821473
          z: 0.459229119003
          w: 0.53768821473
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp2
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539344817
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539368190
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.0587132289312
          y: -0.180700738096
          z: 0.205
        orientation: 
          x: -0.415626937777
          y: 0.572061402818
          z: 0.415626937777
          w: 0.572061402818
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp3
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539344817
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539368190
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.0862581949505
          y: -0.169291239596
          z: 0.205
        orientation: 
          x: -0.369462278271
          y: 0.602907642127
          z: 0.369462278271
          w: 0.602907642127
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp4
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539344817
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539368190
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.111679197936
          y: -0.153713228931
          z: 0.205
        orientation: 
          x: -0.32101976096
          y: 0.630036755335
          z: 0.32101976096
          w: 0.630036755335
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp5
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539344817
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539368190
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.134350288425
          y: -0.134350288425
          z: 0.205
        orientation: 
          x: -0.270598050073
          y: 0.653281482438
          z: 0.270598050073
          w: 0.653281482438
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp6
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539344817
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539368190
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.153713228931
          y: -0.111679197936
          z: 0.205
        orientation: 
          x: -0.218508012224
          y: 0.672498511964
          z: 0.218508012224
          w: 0.672498511964
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp7
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539344817
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539368190
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.169291239596
          y: -0.0862581949505
          z: 0.205
        orientation: 
          x: -0.165070799819
          y: 0.687569364535
          z: 0.165070799819
          w: 0.687569364535
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp8
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539344817
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539368190
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.180700738096
          y: -0.0587132289312
          z: 0.205
        orientation: 
          x: -0.110615871041
          y: 0.698401123334
          z: 0.110615871041
          w: 0.698401123334
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp9
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539344817
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539368190
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.187660784713
          y: -0.0297225483576
          z: 0.205
        orientation: 
          x: -0.0554789586349
          y: 0.704927006965
          z: 0.0554789586349
          w: 0.704927006965
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp10
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539344817
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140337
          nsecs: 539368190
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.19
          y: 1.16341445919e-17
          z: 0.205
        orientation: 
          x: 5.55111512313e-17
          y: 0.707106781187
          z: -5.55111512313e-17
          w: 0.707106781187
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
support_surface_name: table_surface_link
allow_gripper_support_collision: True
attached_object_touch_links: []
minimize_object_distance: False
path_constraints: 
  name: ''
  joint_constraints: []
  position_constraints: []
  orientation_constraints: []
  visibility_constraints: []
planner_id: ''
allowed_touch_objects: []
allowed_planning_time: 5.0
planning_options: 
  planning_scene_diff: 
    name: ''
    robot_state: 
      joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        name: []
        position: []
        velocity: []
        effort: []
      multi_dof_joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        joint_names: []
        transforms: []
        twist: []
        wrench: []
      attached_collision_objects: []
      is_diff: True
    robot_model_name: ''
    fixed_frame_transforms: []
    allowed_collision_matrix: 
      entry_names: []
      entry_values: []
      default_entry_names: []
      default_entry_values: []
    link_padding: []
    link_scale: []
    object_colors: []
    world: 
      collision_objects: []
      octomap: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        origin: 
          position: 
            x: 0.0
            y: 0.0
            z: 0.0
          orientation: 
            x: 0.0
            y: 0.0
            z: 0.0
            w: 0.0
        octomap: 
          header: 
            seq: 0
            stamp: 
              secs: 0
              nsecs: 0
            frame_id: ''
          binary: False
          id: ''
          resolution: 0.0
          data: []
    is_diff: True
  plan_only: True
  look_around: False
  look_around_attempts: 0
  max_safe_execution_cost: 0.0
  replan: False
  replan_attempts: 0
  replan_delay: 2.0
---
target_name: cylinder1
group_name: right_arm
end_effector: right_sdh
possible_grasps: 
  - 
    id: Grasp0
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883412502
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883422103
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -2.32682891838e-17
          y: -0.19
          z: 0.205
        orientation: 
          x: -0.5
          y: 0.5
          z: 0.5
          w: 0.5
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp1
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883412502
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883422103
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.0297225483576
          y: -0.187660784713
          z: 0.205
        orientation: 
          x: -0.459229119003
          y: 0.53768821473
          z: 0.459229119003
          w: 0.53768821473
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp2
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883412502
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883422103
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.0587132289312
          y: -0.180700738096
          z: 0.205
        orientation: 
          x: -0.415626937777
          y: 0.572061402818
          z: 0.415626937777
          w: 0.572061402818
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp3
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883412502
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883422103
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.0862581949505
          y: -0.169291239596
          z: 0.205
        orientation: 
          x: -0.369462278271
          y: 0.602907642127
          z: 0.369462278271
          w: 0.602907642127
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp4
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883412502
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883422103
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.111679197936
          y: -0.153713228931
          z: 0.205
        orientation: 
          x: -0.32101976096
          y: 0.630036755335
          z: 0.32101976096
          w: 0.630036755335
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp5
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883412502
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883422103
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.134350288425
          y: -0.134350288425
          z: 0.205
        orientation: 
          x: -0.270598050073
          y: 0.653281482438
          z: 0.270598050073
          w: 0.653281482438
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp6
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883412502
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883422103
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.153713228931
          y: -0.111679197936
          z: 0.205
        orientation: 
          x: -0.218508012224
          y: 0.672498511964
          z: 0.218508012224
          w: 0.672498511964
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp7
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883412502
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883422103
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.169291239596
          y: -0.0862581949505
          z: 0.205
        orientation: 
          x: -0.165070799819
          y: 0.687569364535
          z: 0.165070799819
          w: 0.687569364535
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp8
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883412502
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883422103
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.180700738096
          y: -0.0587132289312
          z: 0.205
        orientation: 
          x: -0.110615871041
          y: 0.698401123334
          z: 0.110615871041
          w: 0.698401123334
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp9
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883412502
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883422103
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.187660784713
          y: -0.0297225483576
          z: 0.205
        orientation: 
          x: -0.0554789586349
          y: 0.704927006965
          z: 0.0554789586349
          w: 0.704927006965
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
  - 
    id: Grasp10
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883412502
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659, -0.7853981633974483, 0.3490658503988659]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 1397140371
          nsecs: 883422103
        frame_id: world_link
      joint_names: ['right_sdh_knuckle_joint', 'right_sdh_finger_12_joint', 'right_sdh_finger_13_joint', 'right_sdh_finger_22_joint', 'right_sdh_finger_23_joint', 'right_sdh_thumb_2_joint', 'right_sdh_thumb_3_joint']
      points: 
        - 
          positions: [0.0, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988, -0.2243994752564138, 0.5235987755982988]
          velocities: []
          accelerations: []
          effort: []
          time_from_start: 
            secs: 2
            nsecs: 0
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: world_link
      pose: 
        position: 
          x: -0.19
          y: 1.16341445919e-17
          z: 0.205
        orientation: 
          x: 5.55111512313e-17
          y: 0.707106781187
          z: -5.55111512313e-17
          w: 0.707106781187
    grasp_quality: 1.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: 0.0
          y: 0.0
          z: 1.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: right_arm_7_link
        vector: 
          x: -1.0
          y: 0.0
          z: 0.0
      desired_distance: 0.20000000298
      min_distance: 0.10000000149
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: ['cylinder1']
support_surface_name: table_surface_link
allow_gripper_support_collision: True
attached_object_touch_links: []
minimize_object_distance: False
path_constraints: 
  name: ''
  joint_constraints: []
  position_constraints: []
  orientation_constraints: []
  visibility_constraints: []
planner_id: ''
allowed_touch_objects: []
allowed_planning_time: 5.0
planning_options: 
  planning_scene_diff: 
    name: ''
    robot_state: 
      joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        name: []
        position: []
        velocity: []
        effort: []
      multi_dof_joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        joint_names: []
        transforms: []
        twist: []
        wrench: []
      attached_collision_objects: []
      is_diff: True
    robot_model_name: ''
    fixed_frame_transforms: []
    allowed_collision_matrix: 
      entry_names: []
      entry_values: []
      default_entry_names: []
      default_entry_values: []
    link_padding: []
    link_scale: []
    object_colors: []
    world: 
      collision_objects: []
      octomap: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        origin: 
          position: 
            x: 0.0
            y: 0.0
            z: 0.0
          orientation: 
            x: 0.0
            y: 0.0
            z: 0.0
            w: 0.0
        octomap: 
          header: 
            seq: 0
            stamp: 
              secs: 0
              nsecs: 0
            frame_id: ''
          binary: False
          id: ''
          resolution: 0.0
          data: []
    is_diff: True
  plan_only: True
  look_around: False
  look_around_attempts: 0
  max_safe_execution_cost: 0.0
  replan: False
  replan_attempts: 0
  replan_delay: 2.0
---
