target_name: ''
group_name: right_arm
end_effector: right_sdh
possible_grasps: 
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
support_surface_name: table_surface_link
allow_gripper_support_collision: True
attached_object_touch_links: []
minimize_object_distance: False
path_constraints: 
  name: ''
  joint_constraints: []
  position_constraints: []
  orientation_constraints: []
  visibility_constraints: []
planner_id: KPIECEkConfigDefault
allowed_touch_objects: []
allowed_planning_time: 5.0
planning_options: 
  planning_scene_diff: 
    name: ''
    robot_state: 
      joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        name: []
        position: []
        velocity: []
        effort: []
      multi_dof_joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        joint_names: []
        transforms: []
        twist: []
        wrench: []
      attached_collision_objects: []
      is_diff: True
    robot_model_name: ''
    fixed_frame_transforms: []
    allowed_collision_matrix: 
      entry_names: []
      entry_values: []
      default_entry_names: []
      default_entry_values: []
    link_padding: []
    link_scale: []
    object_colors: []
    world: 
      collision_objects: []
      octomap: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        origin: 
          position: 
            x: 0.0
            y: 0.0
            z: 0.0
          orientation: 
            x: 0.0
            y: 0.0
            z: 0.0
            w: 0.0
        octomap: 
          header: 
            seq: 0
            stamp: 
              secs: 0
              nsecs: 0
            frame_id: ''
          binary: False
          id: ''
          resolution: 0.0
          data: []
    is_diff: True
  plan_only: True
  look_around: False
  look_around_attempts: 0
  max_safe_execution_cost: 0.0
  replan: False
  replan_attempts: 0
  replan_delay: 2.0
---
target_name: ''
group_name: right_arm
end_effector: right_sdh
possible_grasps: 
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
support_surface_name: table_surface_link
allow_gripper_support_collision: True
attached_object_touch_links: []
minimize_object_distance: False
path_constraints: 
  name: ''
  joint_constraints: []
  position_constraints: []
  orientation_constraints: []
  visibility_constraints: []
planner_id: KPIECEkConfigDefault
allowed_touch_objects: []
allowed_planning_time: 5.0
planning_options: 
  planning_scene_diff: 
    name: ''
    robot_state: 
      joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        name: []
        position: []
        velocity: []
        effort: []
      multi_dof_joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        joint_names: []
        transforms: []
        twist: []
        wrench: []
      attached_collision_objects: []
      is_diff: True
    robot_model_name: ''
    fixed_frame_transforms: []
    allowed_collision_matrix: 
      entry_names: []
      entry_values: []
      default_entry_names: []
      default_entry_values: []
    link_padding: []
    link_scale: []
    object_colors: []
    world: 
      collision_objects: []
      octomap: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        origin: 
          position: 
            x: 0.0
            y: 0.0
            z: 0.0
          orientation: 
            x: 0.0
            y: 0.0
            z: 0.0
            w: 0.0
        octomap: 
          header: 
            seq: 0
            stamp: 
              secs: 0
              nsecs: 0
            frame_id: ''
          binary: False
          id: ''
          resolution: 0.0
          data: []
    is_diff: True
  plan_only: True
  look_around: False
  look_around_attempts: 0
  max_safe_execution_cost: 0.0
  replan: False
  replan_attempts: 0
  replan_delay: 2.0
---
target_name: ''
group_name: right_arm
end_effector: right_sdh
possible_grasps: 
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
support_surface_name: table_surface_link
allow_gripper_support_collision: True
attached_object_touch_links: []
minimize_object_distance: False
path_constraints: 
  name: ''
  joint_constraints: []
  position_constraints: []
  orientation_constraints: []
  visibility_constraints: []
planner_id: KPIECEkConfigDefault
allowed_touch_objects: []
allowed_planning_time: 5.0
planning_options: 
  planning_scene_diff: 
    name: ''
    robot_state: 
      joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        name: []
        position: []
        velocity: []
        effort: []
      multi_dof_joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        joint_names: []
        transforms: []
        twist: []
        wrench: []
      attached_collision_objects: []
      is_diff: True
    robot_model_name: ''
    fixed_frame_transforms: []
    allowed_collision_matrix: 
      entry_names: []
      entry_values: []
      default_entry_names: []
      default_entry_values: []
    link_padding: []
    link_scale: []
    object_colors: []
    world: 
      collision_objects: []
      octomap: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        origin: 
          position: 
            x: 0.0
            y: 0.0
            z: 0.0
          orientation: 
            x: 0.0
            y: 0.0
            z: 0.0
            w: 0.0
        octomap: 
          header: 
            seq: 0
            stamp: 
              secs: 0
              nsecs: 0
            frame_id: ''
          binary: False
          id: ''
          resolution: 0.0
          data: []
    is_diff: True
  plan_only: True
  look_around: False
  look_around_attempts: 0
  max_safe_execution_cost: 0.0
  replan: False
  replan_attempts: 0
  replan_delay: 2.0
---
target_name: ''
group_name: right_arm
end_effector: right_sdh
possible_grasps: 
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
support_surface_name: table_surface_link
allow_gripper_support_collision: True
attached_object_touch_links: []
minimize_object_distance: False
path_constraints: 
  name: ''
  joint_constraints: []
  position_constraints: []
  orientation_constraints: []
  visibility_constraints: []
planner_id: KPIECEkConfigDefault
allowed_touch_objects: []
allowed_planning_time: 5.0
planning_options: 
  planning_scene_diff: 
    name: ''
    robot_state: 
      joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        name: []
        position: []
        velocity: []
        effort: []
      multi_dof_joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        joint_names: []
        transforms: []
        twist: []
        wrench: []
      attached_collision_objects: []
      is_diff: True
    robot_model_name: ''
    fixed_frame_transforms: []
    allowed_collision_matrix: 
      entry_names: []
      entry_values: []
      default_entry_names: []
      default_entry_values: []
    link_padding: []
    link_scale: []
    object_colors: []
    world: 
      collision_objects: []
      octomap: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        origin: 
          position: 
            x: 0.0
            y: 0.0
            z: 0.0
          orientation: 
            x: 0.0
            y: 0.0
            z: 0.0
            w: 0.0
        octomap: 
          header: 
            seq: 0
            stamp: 
              secs: 0
              nsecs: 0
            frame_id: ''
          binary: False
          id: ''
          resolution: 0.0
          data: []
    is_diff: True
  plan_only: True
  look_around: False
  look_around_attempts: 0
  max_safe_execution_cost: 0.0
  replan: False
  replan_attempts: 0
  replan_delay: 2.0
---
target_name: ''
group_name: right_arm
end_effector: right_sdh
possible_grasps: 
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
  - 
    id: ''
    pre_grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_posture: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      joint_names: []
      points: []
    grasp_pose: 
      header: 
        seq: 0
        stamp: 
          secs: 0
          nsecs: 0
        frame_id: ''
      pose: 
        position: 
          x: 0.0
          y: 0.0
          z: 0.0
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 0.0
    grasp_quality: 0.0
    pre_grasp_approach: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_grasp_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    post_place_retreat: 
      direction: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        vector: 
          x: 0.0
          y: 0.0
          z: 0.0
      desired_distance: 0.0
      min_distance: 0.0
    max_contact_force: 0.0
    allowed_touch_objects: []
support_surface_name: table_surface_link
allow_gripper_support_collision: True
attached_object_touch_links: []
minimize_object_distance: False
path_constraints: 
  name: ''
  joint_constraints: []
  position_constraints: []
  orientation_constraints: []
  visibility_constraints: []
planner_id: KPIECEkConfigDefault
allowed_touch_objects: []
allowed_planning_time: 5.0
planning_options: 
  planning_scene_diff: 
    name: ''
    robot_state: 
      joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        name: []
        position: []
        velocity: []
        effort: []
      multi_dof_joint_state: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        joint_names: []
        transforms: []
        twist: []
        wrench: []
      attached_collision_objects: []
      is_diff: True
    robot_model_name: ''
    fixed_frame_transforms: []
    allowed_collision_matrix: 
      entry_names: []
      entry_values: []
      default_entry_names: []
      default_entry_values: []
    link_padding: []
    link_scale: []
    object_colors: []
    world: 
      collision_objects: []
      octomap: 
        header: 
          seq: 0
          stamp: 
            secs: 0
            nsecs: 0
          frame_id: ''
        origin: 
          position: 
            x: 0.0
            y: 0.0
            z: 0.0
          orientation: 
            x: 0.0
            y: 0.0
            z: 0.0
            w: 0.0
        octomap: 
          header: 
            seq: 0
            stamp: 
              secs: 0
              nsecs: 0
            frame_id: ''
          binary: False
          id: ''
          resolution: 0.0
          data: []
    is_diff: True
  plan_only: True
  look_around: False
  look_around_attempts: 0
  max_safe_execution_cost: 0.0
  replan: False
  replan_attempts: 0
  replan_delay: 2.0
---
